app-infrastructure/configs/picsureui_settings.json
=> Nov 18 2021 release

app-infrastructure/provider.tf, centos-ami/docker-awscli-base.tf, deployment-s3-bucket/provider.tf, non-fisma-environments/data-curation-account/provider.tf, non-fisma-environments/db-subnet-groups/provider.tf, non-fisma-environments/iam-roles/provider.tf, non-fisma-environments/networking/a/provider.tf, non-fisma-environments/networking/b/provider.tf, prod-dns-pointer/provider.tf, s3-deployment-roles/provider.tf
updating provider.tf files to explicit version so terraform doesn't break
=> New ami testing

app-infrastructure/configs/httpd-vhosts.conf, app-infrastructure/configs/picsureui_settings.json, app-infrastructure/httpd-instance.tf, app-infrastructure/variables.tf
Google Analytics ID can now be configured via jenkins using analyticsId as a global variable.
=> [ALS-4884] Add Google Analytics ID

app-infrastructure/scripts/auth_hpds-user_data.sh, app-infrastructure/scripts/open_hpds-user_data.sh
The `docker run` commands need adjustment. Corresponding HPDS changes: https://github.com/hms-dbmi/pic-sure-hpds/pull/82
=> [ALS-5052]: Update hpds scripts to use tomcat docker image

app-infrastructure/configs/banner_config.json, app-infrastructure/configs/pic-sure-schema.sql, app-infrastructure/scripts/auth_hpds-user_data.sh, app-infrastructure/scripts/httpd-user_data.sh, app-infrastructure/scripts/open_hpds-user_data.sh
[ALS-5107] Add configurable banner configuration
=> [ALS-5107] Add configurable banner

app-infrastructure/configs/aggregate-resource.properties
[ALS-5118] Ensure Statistical Visualization Updates deployed in Open PIC-SURE
=> [ALS-5118] Ensure Statistical Visualization Updates deployed in Open PIC-SURE

app-infrastructure/configs/picsureui_settings.json, app-infrastructure/httpd-instance.tf, app-infrastructure/variables.tf
[ALS-5134] Add Google Tag Manager ID
=> [ALS-5134] Add Google Tag Manager ID

app-infrastructure/configs/banner_config.json
[ALS-5123] Banner configuration update
=> [ALS-5123] Banner open leaving

app-infrastructure/dictionary-instance.tf
Just do the best we can with the flat model.  Lot's of past sins still left with poorly named resources.
=> Cleaning up some naming standards

app-infrastructure/configs/banner_config.json, app-infrastructure/s3_roles.tf, app-infrastructure/scripts/httpd-user_data.sh, s3-deployment-roles/s3_roles.tf
The banner_config.json is now correctly uploaded to S3, copied to the HTTPD EC2, and mounted to the HTTPD docker volume.
=> [ALS-5344] Add banner_config.json

app-infrastructure/configs/standalone.xml
[ALS-4498] Checkmarx BDC PIC-SURE SEARCH: Medium finding
=> [ALS-4498] Checkmarx BDC PIC-SURE: Medium finding

app-infrastructure/configs/pic-sure-schema.sql, app-infrastructure/configs/resources-registration.sql, app-infrastructure/configs/standalone.xml
* Should be doing upserts instead of inserts here in case the application already exists and you just want to update the token itself.  
* Will 100% be needed if using a standalone rds.   
* Added secure http only session-cookie
=> ALS-5427: Updating Introspection token

app-infrastructure/auth-hpds-instance.tf, app-infrastructure/dictionary-instance.tf, app-infrastructure/httpd-instance.tf, app-infrastructure/open-hpds-instance.tf, app-infrastructure/variables.tf, app-infrastructure/wildfly-instance.tf
[ALS-5312] Make gss_prefix configurable for instances
=> [ALS-5312] Make gss_prefix configurable for instances

app-infrastructure/configs/picsureui_settings.json, app-infrastructure/httpd-instance.tf, app-infrastructure/variables.tf
- [ALS-5567] Add loginLink to picsureui_settings.json and make configurable via terraform variables
- [ALS-5567] Make helpLink configurable via terraform variables
=> [ALS-5567] Modify infrastructure to make  a configurable value

app-infrastructure/configs/picsureui_settings.json
Added "include_bdc_specific_filters" field to configuration. This field enables filters specific to the BDC environment to be included when set to true.
=> Update configuration in picsureui_settings.json

app-infrastructure/configs/httpd-vhosts.conf, app-infrastructure/configs/psama-db-config.properties, app-infrastructure/configs/psama.env, app-infrastructure/configs/standalone.xml, app-infrastructure/db/auth/V6_Trim_Leading_Spaces.sql, app-infrastructure/scripts/psama-docker.sh, app-infrastructure/scripts/wildfly-docker.sh, app-infrastructure/scripts/wildfly-user_data.sh, app-infrastructure/security-groups.tf, app-infrastructure/variables.tf, app-infrastructure/wildfly-iam.tf, app-infrastructure/wildfly-instance.tf
[ALS-6101] Move psama to it own container
=> [ALS-6101] Move psama to it own container

app-infrastructure/scripts/psama-docker.sh, app-infrastructure/scripts/wildfly-user_data.sh
Added syslog logging configuration to the psama Docker run command, specifying 'wildfly' as the log tag. Updated the Splunk configuration and created a new log directory for psama logs to improve logging and monitoring capabilities.
=> Enable syslog logging for psama Docker container

app-infrastructure/db/auth/V7__Create_Named_dataset_access_rule.sql
[ALS-7197] Add named dataset access rule and update metadata access
=> [ALS-7197] Add named dataset access rule and update metadata access

app-infrastructure/scripts/auth_hpds-user_data.sh, app-infrastructure/scripts/dictionary-user_data.sh, app-infrastructure/scripts/httpd-user_data.sh, app-infrastructure/scripts/open_hpds-user_data.sh, app-infrastructure/scripts/wildfly-user_data.sh
* Splunkforwarder needs to be restarted at the end of the script.
* Moved the restart from after the enable boot start to the end of user-scripts.
=> Fix splunkforwarder

app-infrastructure/db/picsure/V4__Alter_Search_resourceRSPath.sql
- Legacy Search Prototype resource will now point to the dictionary
=> [ALS-7760] Update Legacy Search

app-infrastructure/db/auth/V11__Insert_RAS_Connection.sql
Add SQL migration for inserting RAS connection
=> Add SQL migration for inserting RAS connection

app-infrastructure/provider.tf
Added "template" and "local" providers with specified versions. Updated "random" provider to a newer version. These changes ensure compatibility and extend functionality.
=> Update and add provider configurations in Terraform
